sudo: required

services:
  - docker

before_install:
  - docker build -t pintukumar/docker-react -f Dockerfile.dev .

script:
  - docker run -pintukumar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker-aws-1"  
  env: "React-docker-aws-1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-917520606879"  
  bucket_path: "react-docker-aws-1"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    

