sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker-react-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-nginx npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react3"  
  env: "React3-env"
  bucket_name: "elasticbeanstalk-ap-south-1-917520606879"  
  bucket_path: "react3"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    

