sudo: required

services:
  - docker

before_install:
  - docker build -f docker.io/pintukumar1713122/docker-react -f Dockerfile.dev .

script:
  - docker run docker.io/pintukumar1713122/docker-react npm run test -- --coverage
