sudo: required

services:
  - docker

before_install:
  - docker build -f pintukumar1713122/docker-react -f Dockerfile.dev .

script:
  - docker run pintukumar1713122/docker-react npm run test -- --coverage
