sudo: required

services:
  - docker

before_install:
  - docker build -t pintukumar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pintukumar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker-3-aws"  
  env: "React-docker-3-aws-env"
  bucket_name: "elasticbeanstalk-ap-south-1-917520606879"  
  bucket_path: "react-docker-3-aws"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

    

